# Generated by Django 2.0.8 on 2018-10-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empregados',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='empregados',
        ),
    ]
