# Generated by Django 2.0.8 on 2018-10-27 03:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20181026_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='UserProfile',
        ),
    ]
