# Generated by Django 2.0.9 on 2018-10-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181030_0143'),
        ('users', '0009_auto_20181030_0205'),
    ]

    operations = [
    ]
