# Generated by Django 2.0.8 on 2018-09-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=14)),
                ('categoria', models.CharField(choices=[('1', 'BANHEIRO'), ('2', 'SALA'), ('3', 'LABS')], max_length=1)),
                ('anexo', models.FileField(blank=True, upload_to='post_image')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
