# Generated by Django 2.0.8 on 2018-09-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-01'),
            preserve_default=False,
        ),
    ]
