# Generated by Django 2.0.8 on 2018-09-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('1', 'NOVO'), ('2', 'RESOLVIDO'), ('3', 'EM PROGRESSO')], default='1', max_length=1, null=True),
        ),
    ]
