# Generated by Django 2.0.8 on 2018-09-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20180928_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('1', 'NOVO'), ('2', 'FECHADO'), ('3', 'ABERTO')], default='1', max_length=1, null=True),
        ),
    ]
