# Generated by Django 2.0.8 on 2018-09-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20180928_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('1', 'NOVO'), ('2', 'ABERTO'), ('3', 'FECHADO')], default='1', max_length=1, null=True),
        ),
    ]
