# Generated by Django 2.0.8 on 2018-10-16 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20180928_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='data_entrega',
            field=models.DateTimeField(default='1000-10-10 23:00', verbose_name=datetime.datetime(2018, 10, 22, 22, 47, 44, 904083)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
