# Generated by Django 2.0.8 on 2018-10-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20180928_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dataentrega',
            field=models.DateTimeField(blank=True, default='1000-10-10 10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
