# Generated by Django 2.0.8 on 2018-10-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20181015_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='data_entrega',
            field=models.DateTimeField(blank=True),
        ),
    ]
